### ISSUE TITLE
incorrect URL in go.mod

### ISSUE THREAD

**Issue by nightwolfz** [cristalhq/lvlbp#1]
module gtihub.com/cristalhq/lvlbp

should be

module github.com/cristalhq/lvlbp

**Comment by cristaloleg** [comment]
Oh, my bad :( thank, fixed in https://github.com/cristalhq/lvlbp/commit/848d6e807ad48132124af27bbe63f38bb886578e

**Comment by cristaloleg** [comment]
Also https://github.com/cristalhq/lvlbp/releases/tag/v0.2.0
